/*
 * Cryir
 *
 * User data aggregator.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type Request struct {
	Status string `json:"status,omitempty"`

	DoneServices []string `json:"doneServices,omitempty"`
}
