/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A link describes a connection to an external account.
*/
export class Link {
    /**
    * The unique if of the link.
    */
    'id': string;
    /**
    * The platform of the link.
    */
    'platform': string;
    /**
    * The user id on the platform.
    */
    'platformId': string;
    /**
    * The devhouse account linked to this link.
    */
    'userId': string;
    /**
    * The creation date of the link.
    */
    'createdAt': Date;
    /**
    * The last update of the link (may be always null)
    */
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformId",
            "baseName": "platform_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Link.attributeTypeMap;
    }
    
    public constructor() {
    }
}

