/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StaffMemberPresence {
    'emote'?: string;
    'status': StaffMemberPresenceStatusEnum;
    'text'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emote",
            "baseName": "emote",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StaffMemberPresenceStatusEnum",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StaffMemberPresence.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type StaffMemberPresenceStatusEnum = "online" | "dnd" | "offline" | "idle" | "invisible" ;

