/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TakeoutServices {
    'name'?: string;
    'status'?: TakeoutServicesStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TakeoutServicesStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TakeoutServices.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type TakeoutServicesStatusEnum = "found" | "finished" ;

