#!/usr/bin/env sh

# Determine the Docker organization name
org=$CI_APPLICATION_REPOSITORY
# Set a version tag
VERSION=$CI_APPLICATION_TAG

# Build images for all packages with a Dockerfile, and optionally push them
for package in packages/*; do
    if [ -f $package/Dockerfile ]; then

        if [ -f $package/build.sh ]; then
            sh -c "cd $package && ./build.sh"
        fi
        imagename="$org/"$(echo $package | sed "s/packages\///")

        echo "Building Docker image $imagename..."
        if ! docker build --network="host" -t $imagename:$VERSION $package; then
            echo "Failed to build Docker image for $package"
            exit 1;
        fi
        docker tag $imagename:$VERSION $imagename:latest
        
        if [[ $2 == "push" ]]; then
            echo "Pushing Docker image $imagename..."
            docker push $imagename:$VERSION
            if [ "$LATEST" = true ] ; then
                docker push $imagename:latest
            fi
        fi
    fi
done