service:
  externalPort: 3000
  internalPort: 3000

ingress:
  path: /dialog

livenessProbe:
  path: "/dialog"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/dialog"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"