include:
  - template: Auto-DevOps.gitlab-ci.yml

build:
  stage: build
  image: node
  script:
     - chmod +x ./ci/lerna-docker
     - ./.ci/lerna-docker $CI_APPLICATION_REPOSITORY push ${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'