include:
  - template: Auto-DevOps.gitlab-ci.yml
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'kaniko.gitlab-ci.yml'


variables:
  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg CI_JOB_TOKEN"

test:
  before_script:
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc

.auto-deploy:
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image/v2-3-1:latest
  variables:
    AUTO_DEVOPS_FORCE_DEPLOY_V2: 1
