/*
 * Cryir
 *
 * User data aggregator.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	redis "github.com/go-redis/redis/v8"
	"github.com/streadway/amqp"
	"go.developers-house.xyz/login-group/cryir/logic"
	"go.developers-house.xyz/login-group/cryir/server"
	"log"
	"net/http"
	"os"
)

func main() {
	log.Printf("Server started")

	conn, _ := amqp.Dial(os.Getenv("RABBITMQ_HOST"))
	ch, _ := conn.Channel()

	client := redis.NewFailoverClient(&redis.FailoverOptions{
		SentinelAddrs: []string{
			os.Getenv("REDIS_HOST") + ":" + os.Getenv("REDIS_PORT"),
		},
		SentinelPassword: os.Getenv("REDIS_PASSWORD"), // no password set
		DB:               0,                           // use default DB
	})

	DefaultApiService := logic.NewImplementedApiService(ch, client)
	DefaultApiController := server.NewDefaultApiController(DefaultApiService)

	router := server.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":5000", router))
}
