/*
 * Cryir
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"net/http"
	"os"

	"github.com/go-redis/redis/v8"
	"github.com/rs/zerolog/log"
	"github.com/streadway/amqp"
	openapi "go.developershouse.xyz/login/cryir/go"
	logic "go.developershouse.xyz/login/cryir/logic"
)

func main() {
	log.Printf("Server started")
	amqpClient, err := amqp.Dial(os.Getenv("RABBITMQ_HOST"))
	if err != nil {
		log.Err(err)
		panic(err)
	}
	channel, err := amqpClient.Channel()
	if err != nil {
		log.Err(err)
		panic(err)
	}

	url, err := redis.ParseURL(os.Getenv("REDIS_HOST"))
	if err != nil {
		log.Err(err)
		panic(err)
	}
	redisClient := redis.NewClient(url)

	DefaultApiService := logic.NewImplementedApiService(channel, redisClient)
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	router := openapi.NewRouter(DefaultApiController)

	log.Fatal().Msg(http.ListenAndServe(":5000", router).Error())
}
