openapi: 3.0.0

info:
  title: Amelia
  description: Amelia is the API which allows to interact with the frontend of IMR & to manage data and users
  version: 0.0.1

servers:
  - url: https://developers-house-dev-international-media-referencing-amelia.matthieu-dev.xyz/
    description: First version of the API in production

paths:
  "/data/movies/title/:movieTitle/:language":
    description: Get movie data
    get:
      parameters:
        - in: path
          name: movieTitle
          required: true
          schema:
            type: string
        - in: path
          name: language
          required: true
          schema:
            type: string
      tags:
        - Movie data
      responses:
        200:
          description: Successfully generated S3 link to provide data access
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    statusCode:
                      type: number
                    dataURL:
                      type: string
