openapi: 3.0.0

info:
  title: Amelia
  description: Amelia is the API which allows to interact with the frontend of IMR & to manage data and users
  version: 0.0.1

servers:
  - url: https://developers-house-dev-international-media-referencing-amelia.matthieu-dev.xyz/
    description: First version of the API in production

paths:
  "/data/movies/title":
    description: Get movie data
    get:
      parameters:
        - in: query
          name: movie_title
          required: true
          content:
            text/plain:
              schema:
                type: string
        - in: path
          name: language
          required: true
          content:
            text/plain:
              schema:
                type: string
      tags:
        - Movie data
      responses:
        200:
          description: Successfully found movie in the database
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/MovieDataGlobal"
        404:
          description: Movie not found into the database

components:
  schemas:
    MovieDataGlobal:
      type: object
      required:
        - title
        - company
        - type
        - publicType
        - headers
        - movie
      properties:
        title:
          type: string
        internationalTitle:
          type: string
        company:
          type: string
        releaseDate:
          type: string
        duration:
          type: string
        type:
          type: string
        publicType:
          type: string
        headers:
          type: object
          properties:
            backgroundImage:
              type: string
            moviePoster:
              type: string
            synopsis:
              type: string
            quotation:
              type: string
        movie:
          $ref: "#/components/schemas/ClassicSection"
        casting:
          $ref: "#/components/schemas/CastingSection"
        videos:
          $ref: "#/components/schemas/VideosGlobalSection"
        characters:
          $ref: "#/components/schemas/ClassicSection"
        ost:
          $ref: "#/components/schemas/OSTSection"

    # Summary
    Summary:
      type: array
      items:
        oneOf:
          - $ref: "#/components/schemas/SummaryItem"
          - $ref: "#/components/schemas/SummarySubItem"

    SummaryItem:
      type: object
      required:
        - type
        - to
        - name
      properties:
        type:
          type: string
        to:
          type: string
        name:
          type: string

    SummarySubItem:
      type: object
      required:
        - type
        - to
        - name
        - items
      properties:
        type:
          type: string
        to:
          type: string
        name:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/SummaryItem"

    # Generic section
    ClassicSection:
      type: object
      required:
        - summary
        - body
      properties:
        summary:
          type: array
          items:
            $ref: "#/components/schemas/Summary"
        body:
          type: array
          items:
            $ref: "#/components/schemas/ClassicSectionBody"

    ClassicSectionBody:
      type: array
      items:
        oneOf:
          - $ref: "#/components/schemas/Text"
          - $ref: "#/components/schemas/TextList"
          - $ref: "#/components/schemas/List"

    Text:
      type: object
      required:
        - type
        - name
        - id
        - text
      properties:
        type:
          type: string
        name:
          type: string
        id:
          type: string
        text:
          type: string

    TextList:
      type: object
      required:
        - type
        - name
        - id
        - texts
      properties:
        type:
          type: string
        name:
          type: string
        id:
          type: string
        text:
          type: array
          items:
            type: string

    List:
      type: object
      required:
        - type
        - name
        - id
        - texts
      properties:
        type:
          type: string
        name:
          type: string
        id:
          type: string
        items:
          type: array
          items:
            type: string

    # Casting section
    CastingSection:
      type: object
      required:
        - summary
        - body
      properties:
        summary:
          type: array
          items:
            $ref: "#/components/schemas/Summary"
        body:
          type: array
          items:
            $ref: "#/components/schemas/CastingBody"

    CastingCharacter:
      type: object
      required:
        - name
        - role
      properties:
        imageURL:
          type: string
        name:
          type: string
        role:
          type: string

    CastingBody:
      type: object
      required:
        - name
        - id
        - items
      properties:
        name:
          type: string
        id:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CastingCharacter"

    # Videos section
    VideosGlobalSection:
      type: object
      required:
        - summary
      properties:
        trailers:
          $ref: "#/components/schemas/TrailersSection"
        videos:
          $ref: "#/components/schemas/VideosSection"

    Trailer:
      type: object
      required:
        - title
        - videoID
      properties:
        title:
          type: string
        videoID:
          type: string
        main:
          type: boolean

    Video:
      type: object
      required:
        - title
        - videoID
      properties:
        title:
          type: string
        videoID:
          type: string

    TrailersSection:
      type: object
      required:
        - name
        - id
        - videos
      properties:
        name:
          type: string
        id:
          type: string
        videos:
          type: array
          items:
            $ref: "#/components/schemas/Trailer"

    VideosSection:
      type: object
      required:
        - name
        - id
        - videos
      properties:
        name:
          type: string
        id:
          type: string
        videos:
          type: array
          items:
            $ref: "#/components/schemas/Video"

    # OST section
    OSTSection:
      type: object
      required:
        - summary
        - body
      properties:
        summary:
          type: array
          items:
            $ref: "#/components/schemas/Summary"
        album:
          $ref: "#/components/schemas/Album"
        body:
          type: array
          items:
            $ref: "#/components/schemas/OSTSectionBody"

    Album:
      type: object
      required:
        - name
        - id
        - albumName
        - coverURL
        - interpreters
        - streaming
      properties:
        name:
          type: string
        id:
          type: string
        albumName:
          type: string
        coverURL:
          type: string
        interpreters:
          type: array
          items:
            type: string
        streaming:
          type: array
          items:
            $ref: "#/components/schemas/StreamingService"

    StreamingService:
      type: object
      required:
        - service
        - album
      properties:
        service:
          type: string
        album:
          type: string

    OSTSectionBody:
      type: object
      required:
        - name
        - id
        - tracks
      properties:
        name:
          type: string
        id:
          type: string
        tracks:
          type: array
          items:
            $ref: "#/components/schemas/TrackInformation"

    TrackInformation:
      type: object
      required:
        - title
        - duration
      properties:
        title:
          type: string
        VOTtitle:
          type: string
        duration:
          type: string
        timecode:
          type: string
        description:
          type: string
        characters:
          type: array
          items:
            type: string
        videoID:
          type: string
        lyrics:
          type: string
