openapi: 3.0.0

info:
  title: Scarlet
  description: Simple authentification and user management api
  version: v2

tags:
  - name: service-system
    description: Internal service for the Service functionement.
  - name: user
    description: User management.
  - name: links
    description: Linked accounts management.
  - name: webauth
    description: Linked keys of the user.
  - name: login
    description: login system.
paths:
  "/_healz":
    get:
      operationId: healz
      description: Check the service aliveness.
      tags:
        - service-system
      responses:
        201:
          description: The service is alive.
        500:
          description: The service contains a problem.

  "/user/{user}":
    parameters:
      - in: path
        required: true
        name: id
        schema:
          type: string
          pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
    get:
      description: Fetch a user using his id.
      operationId: getUser
      tags:
        - user
      responses:
        200:
          description: Succesfully got a user from the database.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        404:
          description: Unable to find the user ressource.
        403:
          description: You are not authorized.
        500:
          description: An internal error occured.

    patch:
      operationId: editUser
      description: Edits a user.
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        202:
          description: The user was edited.
        404:
          description: Unable to find the user ressource.
        500:
          description: An internal error occured.

    delete:
      operationId: deleteUser
      description: Delete a user DO NOT USE. CALL CRYIR.
      tags:
        - user
      responses:
        200:
          description: User was deleted.
        404:
          description: Unable to find the user ressource.
        500:
          description: An internal error occured.

  "/user":
    post:
      operationId: createUser
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
      responses:
        200:
          description: The user was succesfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        500:
          description: An internal error occured.

  "/user/{user}/totp":
    parameters:
      - in: path
        name: user
        required: true
        schema:
          type: string
    put:
      tags:
        - links
      description: Generate a TOTP key and link it to the account.
      operationId: generateTOTP
      responses:
        200:
          description: The TOTP account key was generated.
          content:
            application/json:
              schema:
                title: GenerateTotpResponse
                properties:
                  secret:
                    type: string
        404:
          description: Unable to find the user ressource.
        500:
          description: An internal error occured.

  "/user/{user}/links":
    parameters:
      - in: path
        required: true
        name: user
        schema:
          type: string

    get:
      operationId: getUserLinks
      description: Gets the user linked accounts.
      tags:
        - links
      responses:
        200:
          description: Got a linked account list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Link"
        404:
          description: Unable to find the user ressource.
        500:
          description: An internal error occured.

    put:
      operationId: addUserLink
      description: Add a link to the user. DO NOT USE, USE CANDACE INSTEAD.
      tags:
        - links
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewLink"
      responses:
        200:
          description: Added a link to this user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Link"
        404:
          description: Unable to find the user ressource.
        500:
          description: An internal error occured.

  "/user/{user}/links/{link}":
    parameters:
      - in: path
        required: true
        name: user
        schema:
          type: string
      - in: path
        required: true
        name: link
        schema:
          type: string
    delete:
      operationId: deleteUserLink
      description: Deleta a linked account by id.
      tags:
        - links
      responses:
        200:
          description: Succesfully deleted the link
        404:
          description: The user does not exists.
        500:
          description: Internal server error.

  "/user/{user}/webauth":
    parameters:
      - in: path
        name: user
        required: true
        schema:
          type: string
    get:
      operationId: getUserWebAuthKeys
      description: List all the linked public keys of the user.
      tags:
        - webauth
      responses:
        200:
          description: List of the linked keys.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WebAuthKey"
        404:
          description: The user does not exists.
        500:
          description: Internal server error.

    put:
      operationId: addUserWebAuthKey
      description: Add all the linked public keys of the user.
      tags:
        - webauth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebAuthCreate"
      responses:
        202:
          description: Created a webauth key.
        404:
          description: The user does not exists.
        500:
          description: Internal server error.

  "/user/{user}/webauth/{key}":
    parameters:
      - in: path
        name: user
        required: true
        schema:
          type: string
      - in: path
        name: key
        required: true
        schema:
          type: string
    delete:
      operationId: deleteUserWebAuthKey
      description: Delete a webauth key by id.
      tags:
        - webauth
      responses:
        202:
          description: Deleted a key.
        404:
          description: The user does not exists.
        500:
          description: Internal server error.

  "/login":
    post:
      operationId: doLogin
      tags:
        - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        200:
          description: User logged in and returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    title: LoginStatus
                    enum:
                      - UNKNOWN_USER
                      - TWO_FACTOR_REQUIRED
                      - SUCCESS
                      - FAILED
                  user:
                    $ref: "#/components/schemas/User"
                required:
                  - status
        404:
          description: The user does not exists.
        500:
          description: Internal server error.

components:
  schemas:
    # WebAuth Section
    WebAuthKey:
      type: object
      description: WebAuthKey represents a available webauthn key for the user to login with.
      required:
        - id
        - user_id
        - credential_id
        - created_at
      readOnly: true
      properties:
        id:
          type: string
          pattern: uuidv4
          description: The unique identifier for this credential.
        user_id:
          type: string
          pattern: uuidv4
          description: The unique identifier of the user.
        credential_id:
          type: string
          description: The credential id of the auth device.
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    WebAuthCreate:
      type: object
      description: WebAuthCreate represents the needed data to create a key for the user.
      required:
        - credential_id
        - public_key
      properties:
        credential_id:
          type: string
          description: The credential id of the new device.
        public_key:
          type: array
          items:
            type: number
          description: The public key as an array of bytes.

    # User section
    User:
      type: object
      description: User is the representation of a Developer's House user.
      required:
        - id
        - username
        - pub
        - roles
        - avatar
        - a2f
        - created_at
      properties:
        id:
          type: string
          pattern: uuidv4
          description: The unique id of the user.
        username:
          type: string
          description: The username of the user.
        pub:
          type: boolean
          description: Is the user account a private account?
        roles:
          type: integer
          description: The roles attribued to this user.
        ban:
          type: string
          description: Will be filled by the reason if the user is banned.
        avatar:
          type: string
          description: The avatar associated to the user in s3
        a2f:
          type: boolean
          description: Is two factor auth enabled for this user?
        updated_at:
          type: string
          format: date-time
          description: The date of the last update of this account.
        created_at:
          type: string
          format: date-time
          description: The creation date of the account.

    UserCreate:
      type: object
      description: UserCreate described the data needed for a user to be created.
      required:
        - platform
        - platform_id
        - username
        - pub
        - avatar
      properties:
        platform:
          type: string
          description: The name of the platform user to log-in.
        platform_id:
          description: The user id of the user on the login platform.
          type: string
        username:
          description: The username of the new user.
          type: string
        pub:
          description: Is the account public by default
          type: boolean
        avatar:
          description: The already-uploaded user account on s3.
          type: string

    UserUpdate:
      type: object
      description: UserUpdate described all the available fields for the user.
      properties:
        username:
          description: The new username of the user.
          type: string
        pub:
          description: The new private setting of the user.
          type: boolean
        roles:
          description: The new role of the user.
          type: integer
        twofa:
          description: The new 2fa setting of the user.
          type: boolean
        avatar:
          description: The new avatar of the user.
          type: string

    # Link section
    Link:
      type: object
      description: A link describes a connection to an external account.
      required:
        - id
        - platform
        - platform_id
        - user_id
        - created_at
      readOnly: true
      properties:
        id:
          description: The unique if of the link.
          type: string
          pattern: uuidv4
        platform:
          description: The platform of the link.
          type: string
        platform_id:
          description: The user id on the platform.
          type: string
        user_id:
          description: The devhouse account linked to this link.
          type: string
        created_at:
          description: The creation date of the link.
          type: string
          format: date-time
        updated_at:
          description: The last update of the link (may be always null)
          type: string
          format: date-time

    NewLink:
      description: NewLink represents the data needed for a link to be created.
      type: object
      required:
        - platform
        - platform_id
      properties:
        platform:
          description: The platform used.
          type: string
        platform_id:
          description: The user id on this platform.
          type: string

    Login:
      description: Login request.
      type: object
      required:
        - with_platform
      properties:
        with_platform:
          type: object
          properties:
            platform_id:
              type: string
            platform_name:
              type: string
        with_webauthn:
          type: object
        with_otp:
          type: object
          properties:
            code:
              type: integer