include:
  - template: Auto-DevOps.gitlab-ci.yml

sentry_release:
  stage: .post
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases new -p ellie $CI_COMMIT_SHORT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHORT_SHA
