/*
 * Cryir
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"CreateTakeout",
			strings.ToUpper("Put"),
			"/takeouts/{user}",
			c.CreateTakeout,
		},
		{
			"GetTakeouts",
			strings.ToUpper("Get"),
			"/takeouts/{user}",
			c.GetTakeouts,
		},
		{
			"HealthGet",
			strings.ToUpper("Get"),
			"/health",
			c.HealthGet,
		},
		{
			"RequestDelete",
			strings.ToUpper("Put"),
			"/deletion/{user}",
			c.RequestDelete,
		},
	}
}

// CreateTakeout -
func (c *DefaultApiController) CreateTakeout(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	user := params["user"]

	result, err := c.service.CreateTakeout(r.Context(), user)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetTakeouts -
func (c *DefaultApiController) GetTakeouts(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	user := params["user"]

	result, err := c.service.GetTakeouts(r.Context(), user)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// HealthGet -
func (c *DefaultApiController) HealthGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.HealthGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// RequestDelete -
func (c *DefaultApiController) RequestDelete(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	user := params["user"]

	result, err := c.service.RequestDelete(r.Context(), user)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
