/*
 * Cryir
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// CreateTakeout - 
func (s *DefaultApiService) CreateTakeout(ctx context.Context, user string) (ImplResponse, error) {
	// TODO - update CreateTakeout with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Takeout{}) or use other options such as http.Ok ...
	//return Response(200, Takeout{}), nil

	//TODO: Uncomment the next line to return response Response(404, string{}) or use other options such as http.Ok ...
	//return Response(404, string{}), nil

	//TODO: Uncomment the next line to return response Response(415, string{}) or use other options such as http.Ok ...
	//return Response(415, string{}), nil

	//TODO: Uncomment the next line to return response Response(0, string{}) or use other options such as http.Ok ...
	//return Response(0, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTakeout method not implemented")
}

// GetTakeouts - 
func (s *DefaultApiService) GetTakeouts(ctx context.Context, user string) (ImplResponse, error) {
	// TODO - update GetTakeouts with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Takeout{}) or use other options such as http.Ok ...
	//return Response(200, []Takeout{}), nil

	//TODO: Uncomment the next line to return response Response(404, string{}) or use other options such as http.Ok ...
	//return Response(404, string{}), nil

	//TODO: Uncomment the next line to return response Response(415, string{}) or use other options such as http.Ok ...
	//return Response(415, string{}), nil

	//TODO: Uncomment the next line to return response Response(0, string{}) or use other options such as http.Ok ...
	//return Response(0, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTakeouts method not implemented")
}

// RequestDelete - 
func (s *DefaultApiService) RequestDelete(ctx context.Context, user string) (ImplResponse, error) {
	// TODO - update RequestDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	//return Response(200, string{}), nil

	//TODO: Uncomment the next line to return response Response(404, string{}) or use other options such as http.Ok ...
	//return Response(404, string{}), nil

	//TODO: Uncomment the next line to return response Response(415, string{}) or use other options such as http.Ok ...
	//return Response(415, string{}), nil

	//TODO: Uncomment the next line to return response Response(0, string{}) or use other options such as http.Ok ...
	//return Response(0, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequestDelete method not implemented")
}

