/*
 * Cryir
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Takeout - A takeout and his status.
type Takeout struct {

	Id string `json:"id"`

	Link string `json:"link,omitempty"`

	Expire int32 `json:"expire"`

	User string `json:"user"`

	Status string `json:"status,omitempty"`

	Services []TakeoutServices `json:"services"`
}
