apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket-{{ template "trackableappname" . }}
spec:
  generateBucketName: ellie-{{ template "trackableappname" . }}
  storageClassName: rook-ceph-bucket
