apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: website-{{ template "trackableappname" . }}
spec:
  clientName: Website ({{ template "trackableappname" . }})
  grantTypes:
    - implicit
  responseTypes:
    - token
  scope: "account.* websocket.*"
  secretName: oauth-client-{{ template "trackableappname" . }}
  # these are optional
  redirectUris:
  {{- if .Values.service.commonName }}
    - https://{{ template "fhostname" .Values.service.commonName }}/callback
  {{- end }}
    - https://{{ template "fhostname" .Values.service.url }}/callback
  {{- if .Values.service.additionalHosts }}
  {{- range $host := .Values.service.additionalHosts }}
    - https://{{ template "fhostname" $host }}/callback
  {{- end -}}
  {{- end }}
  audience:
    - abdera
  tokenEndpointAuthMethod: none
