/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SelfUser {
    'id': string;
    'username'?: string;
    '_private': string;
    'roles': number;
    'avatar'?: string;
    'dataCollection': boolean;
    'premium': boolean;
    'ban'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "_private",
            "baseName": "private",
            "type": "string",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "number",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataCollection",
            "baseName": "dataCollection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "premium",
            "baseName": "premium",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "ban",
            "baseName": "ban",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SelfUser.attributeTypeMap;
    }
    
    public constructor() {
    }
}

