/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TakeoutServices } from './TakeoutServices';
import { HttpFile } from '../http/http';

export class Takeout {
    'uuid': string;
    'link'?: string;
    'expire': number;
    'services'?: Array<TakeoutServices>;
    'status': TakeoutStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "expire",
            "baseName": "expire",
            "type": "number",
            "format": ""
        },
        {
            "name": "services",
            "baseName": "services",
            "type": "Array<TakeoutServices>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TakeoutStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Takeout.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type TakeoutStatusEnum = "pending" | "failed" | "finished" | "processing" ;

