openapi: 3.0.0
info:
  description: User data aggregator.
  title: Cryir
  version: v1
servers:
  - url: /
paths:
  /requests:
    post:
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            type:
              schema:
                $ref: '#/components/schemas/Request'
          description: The data request was created.
        "400":
          description: Bad request.
      summary: Creates a data request.
  /requests/{request}:
    get:
      parameters:
        - explode: false
          in: path
          name: request
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            type:
              schema:
                $ref: '#/components/schemas/Request'
          description: The data request exists and was returned.
      summary: Gets the status of a request
  /requests/{request}/finalizers:
    post:
      parameters:
        - explode: false
          in: path
          name: request
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          description: The finalizer was registered.
        "404":
          description: The request doesn't exist.
      summary: Register a finalizer for a request.
    patch:
      parameters:
        - explode: false
          in: path
          name: request
          required: true
          schema:
            type: string
          style: simple
        - explode: false
          in: query
          name: finished
          schema:
            type: boolean
          style: simple
      responses:
        "200":
          description: The finalizer status was updated.
        "404":
          description: The request doesn't exist.
      summary: Updates the status of a finalizer
components:
  schemas:
    Request:
      type: object
      properties:
        status:
          type: string
        doneServices:
          items:
            type: string
          type: array
        url:
          oneOf:
            - type: string