openapi: 3.0.0
info:
  description: User data aggregator.
  title: Cryir
  version: v1
servers:
  - url: /
paths:
  /requests:
    post:
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            type:
              schema:
                $ref: '#/components/schemas/Request'
          description: The data request was created.
        "400":
          description: Bad request.
      summary: Creates a data request.
  /requests/{request}:
    get:
      parameters:
        - explode: false
          in: path
          name: request
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            type:
              schema:
                $ref: '#/components/schemas/Request'
          description: The data request exists and was returned.
      summary: Gets the status of a request
  /requests/user/{userId}:
    get:
      parameters:
        - explode: false
          in: path
          name: userId
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            type:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    link:
                      type: string
                    expire:
                      type: number
          description: The data request exists and was returned.
      summary: Gets the status of a request
components:
  schemas:
    Request:
      type: object
      properties:
        status:
          type: string
        doneServices:
          items:
            type: string
          type: array
        url:
          oneOf:
            - type: string