/*
 * Cryir
 *
 * User data aggregator.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"RequestsPost",
			strings.ToUpper("Post"),
			"/requests",
			c.RequestsPost,
		},
		{
			"RequestsRequestFinalizersPost",
			strings.ToUpper("Post"),
			"/requests/{request}/finalizers",
			c.RequestsRequestFinalizersPost,
		},
		{
			"RequestsRequestGet",
			strings.ToUpper("Get"),
			"/requests/{request}",
			c.RequestsRequestGet,
		},
	}
}

// RequestsPost - Creates a data request.
func (c *DefaultApiController) RequestsPost(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.RequestsPost()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// RequestsRequestFinalizersPost - Register a finalizer for a request.
func (c *DefaultApiController) RequestsRequestFinalizersPost(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	request := params["request"]
	result, err := c.service.RequestsRequestFinalizersPost(request)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// RequestsRequestGet - Gets the status of a request
func (c *DefaultApiController) RequestsRequestGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	request := params["request"]
	result, err := c.service.RequestsRequestGet(request)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
