/*
 * Cryir
 *
 * User data aggregator.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// RequestsPost - Creates a data request.
func (s *DefaultApiService) RequestsPost() (interface{}, error) {
	// TODO - update RequestsPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'RequestsPost' not implemented")
}

// RequestsRequestFinalizersPost - Register a finalizer for a request.
func (s *DefaultApiService) RequestsRequestFinalizersPost(request string) (interface{}, error) {
	// TODO - update RequestsRequestFinalizersPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'RequestsRequestFinalizersPost' not implemented")
}

// RequestsRequestGet - Gets the status of a request
func (s *DefaultApiService) RequestsRequestGet(request string) (interface{}, error) {
	// TODO - update RequestsRequestGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'RequestsRequestGet' not implemented")
}
