include:
  - template: Auto-DevOps.gitlab-ci.yml
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'kaniko.gitlab-ci.yml'
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'helm.gitlab-ci.yml'

build:
  before_script:
    - echo "@developers-house:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
          export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
          export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
          export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
          export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi

cypress:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .npm/
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  parallel:
    matrix:
      - RUNNER: [firefox, chrome]
  script:
    - yarn
    - yarn run build
    - yarn run start &
    - npx cypress run --browser $RUNNER
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day