/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthorizationClient } from './AuthorizationClient';
import { HttpFile } from '../http/http';

export class Authorization {
    'client': AuthorizationClient;
    'scopes': Array<string>;
    'audiences': Array<string>;
    'grantedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "client",
            "baseName": "client",
            "type": "AuthorizationClient",
            "format": ""
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "audiences",
            "baseName": "audiences",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "grantedAt",
            "baseName": "grantedAt",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return Authorization.attributeTypeMap;
    }
    
    public constructor() {
    }
}

