/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StaffMember } from './StaffMember';
import { HttpFile } from '../http/http';

export class Project {
    'name': string;
    'normalizedName': string;
    'logo': string;
    'banner'?: string;
    'shortDescription': string;
    'longDescription': string;
    'members': Array<StaffMember>;
    'managers': Array<StaffMember>;
    'link'?: string;
    'markdownS3'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "normalizedName",
            "baseName": "normalizedName",
            "type": "string",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "banner",
            "baseName": "banner",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "shortDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "longDescription",
            "baseName": "longDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<StaffMember>",
            "format": ""
        },
        {
            "name": "managers",
            "baseName": "managers",
            "type": "Array<StaffMember>",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "markdownS3",
            "baseName": "markdown_s3",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Project.attributeTypeMap;
    }
    
    public constructor() {
    }
}

