/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StaffMemberPresence } from './StaffMemberPresence';
import { StaffMemberRole } from './StaffMemberRole';
import { StaffMemberSocials } from './StaffMemberSocials';
import { HttpFile } from '../http/http';

export class StaffMember {
    'username': string;
    'presence': StaffMemberPresence;
    'socials': Array<StaffMemberSocials>;
    'role': StaffMemberRole;
    'avatar': string;
    'discriminator': string;
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "presence",
            "baseName": "presence",
            "type": "StaffMemberPresence",
            "format": ""
        },
        {
            "name": "socials",
            "baseName": "socials",
            "type": "Array<StaffMemberSocials>",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "StaffMemberRole",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string",
            "format": ""
        },
        {
            "name": "discriminator",
            "baseName": "discriminator",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StaffMember.attributeTypeMap;
    }
    
    public constructor() {
    }
}

