/**
 * Abdera API
 * A simple api for the ressources needed by the website.
 *
 * OpenAPI spec version: 1.6.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StaffMemberSocials {
    'link'?: string;
    'name'?: string;
    'icon'?: StaffMemberSocialsIconEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "StaffMemberSocialsIconEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StaffMemberSocials.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type StaffMemberSocialsIconEnum = "gitlab" | "github" | "discord" | "website" | "stackoverflow" ;

