apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-http
spec:
  rules:
  - host: ${DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meta-http
            port:
              number: 80
