include:
  - template: Auto-DevOps.gitlab-ci.yml
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'kaniko.gitlab-ci.yml'
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'helm.gitlab-ci.yml'

build:
  before_script:
    - echo "@developers-house:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc


package:
  stage: build
  image: timbru31/java-node
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  only:
    changes:
      - openapi.yaml
      - gen/*
    refs:
      - master
  script:
    - yarn
    - yarn gen:client
    - cd gen
    - apt-get update -y
    - apt-get install jq -y
    - yarn
    - yarn build
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee --append .npmrc
    - VERSION=$(jq .version package.json)
    - echo "${VERSION:1:${#VERSION}-2}"
    - yarn publish --new-version "${VERSION:1:${#VERSION}-2}"

test:
  image: timbru31/java-node
  script:
    - echo "@developers-house:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - yarn install
    - yarn build
    - rm -r dist
    - npx jest --ci --reporters=default --reporters=jest-junit
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
