include:
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'base.gitlab-ci.yml'

build:
  before_script:
    - echo "@developers-house:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc

# Publish the npm package
package:
  stage: build
  image: timbru31/java-node # We need java in the container
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  only:
    changes:
      - openapi.yaml
      - gen/*
    refs:
      - master
  before_script:
    - echo "@developers-house:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
    - apt-get update -y
    - apt-get install jq -y
    - npm i
    - npm run gen:client
    - cd gen

    # We set the repository url to the project npm registry endpoint because gitlab does not support instance-level publishing of npm packages
    - echo "@developers-house:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  
    - npm i
    - npm run build

    # This may be replaced by an automatic bump.
    - VERSION=$(jq .version package.json)
    - echo "${VERSION:1:${#VERSION}-2}"
    - npm publish


# Report the test results
test:
  image: timbru31/java-node
  before_script:
    - echo "@developers-house:registry=https://gitlab.com/api/v4/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
    - yarn install
    - yarn build
    - rm -r dist
    - npx jest --passWithNoTests --ci --reporters=default --reporters=jest-junit
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml # GitLab only supports junit test results.
