include:
  - template: Auto-DevOps.gitlab-ci.yml
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'kaniko.gitlab-ci.yml'

variables:
  HELM_UPGRADE_VALUES_FILE: 'deploy.yaml'
  TEST_DISABLED: 'true'
  PERFORMANCE_DISABLED: 'true'
  CODE_QUALITY_DISABLED: 'true'
  SECRET_DETECTION_DISABLED: 'true'
  SAST_DISABLED: 'true'
