variables:
  DOCKER_BUILDKIT: '1'

include:
  - template: Auto-DevOps.gitlab-ci.yml
  - project: 'developers-house/dev/gitlab-ci-collection'
    ref: master
    file: 'kaniko.gitlab-ci.yml'
variables:
  AUTO_DEVOPS_CHART_REPOSITORY: 'https://charts.helm.sh/stable'
  HELM_UPGRADE_VALUES_FILE: 'deploy.yaml'
  TEST_DISABLED: 'true'
  PERFORMANCE_DISABLED: 'true'
  CODE_QUALITY_DISABLED: 'true'
  SECRET_DETECTION_DISABLED: 'true'
  SAST_DISABLED: 'true'

.auto-deploy:
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image/v2-3-1:latest
  variables:
    AUTO_DEVOPS_FORCE_DEPLOY_V2: 1
