version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
  redis:
    image: redis
    restart: always
  cryir:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: "6379"