/*
 * Cryir
 *
 * User data aggregator.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"go.developers-house.xyz/login-group/cryir/server"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := server.NewDefaultApiService()
	DefaultApiController := server.NewDefaultApiController(DefaultApiService)

	router := server.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":5000", router))
}
