include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  DOCKER_BUILDKIT: '1'

node_build:
  image: node
  script:
    - yarn install
    - yarn build
  cache:
    key: node-modules
    paths:
      - node_modules
  stage: build
  artifacts:
    name: 'React build'
    paths:
      - build

build:
  needs:
    - node_build
  dependencies:
    - node_build