kind: OAuth2Client
apiVersion: hydra.ory.sh/v1alpha1
metadata:
  name: website-dev
  namespace: default
spec:
  audience:
    - abdera
  clientName: Website (DEV)
  grantTypes:
    - implicit
  hydraAdmin: {}
  redirectUris:
    - 'http://localhost:3000/callback'
  responseTypes:
    - token
  scope: "account.* websocket.*"
  secretName: website-dev
  tokenEndpointAuthMethod: none
