/*
 * Cryir
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
