/*
 * Cryir
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TakeoutServices struct {

	Status string `json:"status"`

	Name string `json:"name,omitempty"`
}
