apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  annotations:
    app.gitlab.com/app: {{ .Values.gitlab.app | quote }}
    app.gitlab.com/env: {{ .Values.gitlab.env | quote }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        app.gitlab.com/app: {{ .Values.gitlab.app | quote }}
        app.gitlab.com/env: {{ .Values.gitlab.env | quote }}
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.secrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
{{- if .Values.tracing.enabled }}
        - name: jaeger-agent
          image: "{{ .Values.tracing.image }}"
          ports:
            - name: zk-compact-trft
              containerPort: 5775
              protocol: UDP
            - name: config-rest
              containerPort: 5778
              protocol: TCP
            - name: jg-compact-trft
              containerPort: 6831
              protocol: UDP
            - name: jg-binary-trft
              containerPort: 6832
              protocol: UDP
            - name: admin-http
              containerPort: 14271
              protocol: TCP
          command:
          - "/go/bin/agent-linux"
          - "--reporter.grpc.host-port=dns:///simplest-collector-headless.observability:14250"
{{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.application.secretName }}
          envFrom:
          {{- else if .Values.oauthClient.enabled }}
          envFrom:
          {{- else if .Values.storageBucket.enabled }}
          envFrom:
          {{- else if .Values.application.secretName }}
            - secretRef:
                name: {{ .Values.application.secretName }}
          {{- end }}
          {{- if .Values.oauthClient.enabled }}
            - secretRef:
                name: oauth-client-{{ include "..fullname" . }}
          {{- end }}
          {{- if .Values.storageBucket.enabled }}
            - secretRef:
                name: bucket-{{ include "..fullname" . }}
            - configMapRef:
                name: bucket-{{ include "..fullname" . }}
          {{- end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
{{- if eq .Values.health.livenessProbe.probeType "httpGet" }}
            httpGet:
              path: {{ .Values.health.livenessProbe.path }}
              scheme: {{ .Values.health.livenessProbe.scheme }}
              port: {{ .Values.service.internalPort }}
{{- else if eq .Values.health.livenessProbe.probeType "tcpSocket" }}
            tcpSocket:
              port: {{ .Values.service.internalPort }}
{{- else if eq .Values.health.livenessProbe.probeType "exec" }}
            exec:
              command:
                {{ toYaml .Values.health.livenessProbe.command | indent 16 }}
{{- end }}
          readinessProbe:
{{- if eq .Values.health.readinessProbe.probeType "httpGet" }}
            httpGet:
              path: {{ .Values.health.readinessProbe.path }}
              scheme: {{ .Values.health.readinessProbe.scheme }}
              port: {{ .Values.service.internalPort }}
{{- else if eq .Values.health.readinessProbe.probeType "tcpSocket" }}
            tcpSocket:
              port: {{ .Values.service.internalPort }}
{{- else if eq .Values.health.readinessProbe.probeType "exec" }}
            exec:
              command:
                {{ toYaml .Values.health.readinessProbe.command | indent 16 }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
