{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "..serviceAccountName" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    app.gitlab.com/app: {{ .Values.gitlab.app | quote }}
    app.gitlab.com/env: {{ .Values.gitlab.env | quote }}
{{- end }}
