default:
  image: node:12
  before_script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee --append .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - release

publish:
  stage: release
  script:
    - apt-get update -y
    - apt-get install jq -y
    - yarn
    - yarn build
    - VERSION=$(jq .version package.json)
    - echo "${VERSION:1:${#VERSION}-2}"
    - yarn publish --new-version "${VERSION:1:${#VERSION}-2}"
