include:
  - template: Auto-DevOps.gitlab-ci.yml

sentry_release:
  stage: .post
  image: getsentry/sentry-cli
  script:
    - VERSION=$(sentry-cli releases propose-version)
    - sentry-cli releases new -p scarlet $CI_COMMIT_SHORT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHORT_SHA
